sudo: required

language: python
python:
  - "2.7"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
  - AWS_S3_BUCKET_NAME=elba-registry
  - AWS_REGION=ap-northeast-1

before_install:
  - docker --version
  - pip install awscli
  - pip install ansible
  - cd deploy

script:
  - bash ./docker-build-image.sh

deploy:
  # Push elba/registry image to aws ecr
  - provider: script
    script: 
      - bash ./docker-push-image.sh
    on:
      branch: master

  # Deploy frontend public to s3 bucket
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY}"
    secret_access_key: "${AWS_SECRET_KEY}"
    bucket: "${AWS_S3_BUCKET_NAME}"
    region: "${AWS_REGION}"
    local_dir: ../public
    upload-dir: public
    on:
      branch: master

  # Pull and run registry image remotely by ansible
  - provider: script
    script: 
      - openssl enc -d -des-ecb -k $ENCRYPT_KEY
        -in ./deploy/docker-compose.prod.yml.enc -out deploy/docker-compose.prod.yml &&
        openssl enc -d -des-ecb -k $ENCRYPT_KEY
        -in ./deploy/key.pem.enc -out deploy/key.pem &&
        echo "$REGISTRY_DOMAIN" > inventory && 
        export ANSIBLE_HOST_KEY_CHECKING=false &&
        ansible-playbook -i inventory -u $REGISTRY_USER --private-key key.pem playbook.yml
    on:
      branch: master
