sudo: required
language: python

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
  - AWS_S3_BUCKET_NAME=elba-registry
  - AWS_REGION=ap-northeast-1

before_install:
  - docker --version
  - pip install awscli
  - openssl aes-256-cbc -K $encrypted_6154f6f18afb_key -iv $encrypted_6154f6f18afb_iv
    -in deploy/docker-compose.prod.yml.enc -out deploy/docker-compose.prod.yml -d

script:
  - cd deploy && bash ./docker-build-image.sh

deploy:
  # Push elba/registry image to aws ecr
  - provider: script
    script: 
      - bash ./docker-push-image.sh
    on:
      branch: master

  # Deploy frontend public to s3 bucket
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY}"
    secret_access_key: "${AWS_SECRET_KEY}"
    bucket: "${AWS_S3_BUCKET_NAME}"
    region: "${AWS_REGION}"
    local_dir: ../public
    upload-dir: public
    on:
      branch: master

  # Pull and run registry by ansible
  # - provider: script
  #   script: 
  #     - cd deploy
  #     - ansible-playbook playbook.yml
  #   on:
  #     branch: master
