sudo: required
language: python

services:
  - docker

env:
  global:
  - AWS_S3_BUCKET_NAME=elba-registry
  - AWS_REGION=ap-northeast-1

before_install:
  - pip install awscli

script:
  - cd deploy && sh ./docker-build-image.sh

deploy:
  # Push elba/registry image to aws ecr
  - provider: script
    script: 
      - cd deploy && sh ./docker-push-image.sh
    on:
      branch: master

  # Deploy frontend public to s3 bucket
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY}"
    secret_access_key: "${AWS_SECRET_KEY}"
    bucket: "${AWS_S3_BUCKET_NAME}"
    region: "${AWS_REGION}"
    local_dir: ../public
    upload-dir: public
    on:
      branch: master

  # Pull and run registry by ansible
  # - provider: script
  #   script: 
  #     - cd deploy
  #     - ansible-playbook playbook.yml
  #   on:
  #     branch: master
