version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx-conf.conf:/etc/nginx/nginx.conf:ro
      - /var/lib/nginx/certs:/etc/nginx/certs:ro
      - ./public:/app/public:ro
      - storage:/app/storage:ro

  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_DB=elba
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./deploy/backend.Dockerfile
    container_name: backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/elba
      - BIND_TO=0.0.0.0:17000
      - MAX_UPLOAD_SIZE=31457280
      - STORAGE_PATH=./tmp/storage
      - BACKEND_URL=https://elba.chaos.tk
      - CDN_URL=https://dl.chaos.tk
      - SEARCH_ENGINE_PATH=./tmp/search
      - LOCAL_INDEX_PATH=./tmp/index
      - LOCAL_INDEX_NO_SYNC=false
      - REMOTE_INDEX_URL=https://github.com/andylokandy/index.git
      - REMOTE_INDEX_USER=
      - REMOTE_INDEX_PWD=
    expose:
      - 17000
    volumes:
      # Mount the src/ directory so we don't have to rebuild the Docker image
      # when we want to change some code
      - ./src:/app/src:ro
      - ./Cargo.toml:/app/Cargo.toml:ro
      - local-index:/app/tmp/index
      - search-index:/app/tmp/search
      - storage:/app/tmp/storage

volumes:
  postgres-data:
  local-index:
  search-index:
  storage:
