version: '2'

services:
  nginx:
    image: nginx:1.15.10-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx-conf.conf:/etc/nginx/nginx.conf:ro
      - /var/lib/nginx/certs:/etc/nginx/certs:ro
      - ./public:/app/public:ro
      - storage:/app/storage:ro

  postgres:
    image: postgres:10.7-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=elba
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: elba/backend:latest
    container_name: backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/elba
      - BIND_TO=0.0.0.0:17000
      - MAX_UPLOAD_SIZE=31457280
      - STORAGE_PATH=./tmp/storage
      - BACKEND_URL=https://elba.chaos.tk
      - CDN_URL=https://dl.chaos.tk
      - SEARCH_ENGINE_PATH=./tmp/search
      - LOCAL_INDEX_PATH=./tmp/index
      - LOCAL_INDEX_NO_SYNC=true
      - REMOTE_INDEX_URL=https://github.com/andylokandy/index.git
      - REMOTE_INDEX_USER=
      - REMOTE_INDEX_PWD=
    ports:
      - 127.0.0.1:17000:17000
    volumes:
      - local-index:/app/tmp/index
      - search-index:/app/tmp/search
      - storage:/app/tmp/storage

volumes:
  postgres-data:
  local-index:
  search-index:
  storage:
