version: '2'

services:
  registry-builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: elba/registry:builder
    container_name: registry-builder
    volumes:
      - ../:/app
      - cargo-cache:/root/.cargo/registry
      - target-cache:/app/target

volumes:
  cargo-cache:
  target-cache:
