version: '2'

services:
  postgres:
    image: postgres:10.7-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=elba
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  registry:
    image: elba/registry:latest
    container_name: registry
    restart: unless-stopped
    ports:
      - 127.0.0.1:17000:17000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/elba
    volumes:
      - storage:/app/tmp/storage

volumes:
  postgres-data:
  storage:
