[package]
authors = ["andylokandy <andylokandy@hotmail.com>"]
edition = "2018"
name = "simsearch"
version = "0.1.0"

[dependencies]
strsim = "0.9.1"

[dev-dependencies]
json = "0.11.13"
lazy_static = "1.3.0"
quickcheck = "0.8"
quickcheck_macros = "0.8"
itertools = "0.8"
